### ISSUE TITLE
Large object warning

### ISSUE THREAD

**Issue by jrbourbeau** [eriknw/afar#11]
When using 

```python
import afar

with afar.run, remotely:
    # Dask things here
```

today, I ended up triggering Dask's "Large object of size XXX detected in task graph" warning message (shown below):

```
/Users/james/projects/dask/distributed/distributed/worker.py:3862: UserWarning: Large object of size 1.00 MiB detected in task graph: 
  (<afar.core.MagicFunction object at 0x168b1c610>, ('result',), {})
Consider scattering large objects ahead of time
with client.scatter to reduce scheduler burden and 
keep data on workers

    future = client.submit(func, big_data)    # bad

    big_future = client.scatter(big_data)     # good
    future = client.submit(func, big_future)  # good
  warnings.warn(
```

Functionally this is totally fine and everything ran successfully. However, this big red warning may be scary to users (in particular, those new to Dask). 

We might consider:

1. Scattering the `MagicFunction` object ahead of time and passing the corresponding `Future` around
2. Mention the "Large object of size XXX detected in task graph" warning in the README so folks are at least aware it's (potentially) expected

**Comment by eriknw** [comment]
Oh I see.  Yeah, it will probably be easy to pull in an object from the outer scope that's larger than 1 MiB.

`client.scatter` could work, but I imagine the data could be sent to a different worker than where the task will be run.  Unlike `submit`, I can't pass `resources=` to `scatter`.  This seems less than ideal to me.

I think the warning is useful (although the limit seems kinda low for `afar`), so I like your suggestion of adding a comment in the README.  The user is free to ignore it or scatter the data themselves.

One can also do:
```python
run = afar.run(data={'df': df})
with run, remotely:
    ...
```
It probably makes sense to scatter the data here, because it may get used more than once.
